import { withSerializableTransaction } from './serializableTransaction.js';
import { randomUUID } from 'node:crypto';
import { prisma } from './prisma.js';
import { inboundAddresses, mailbox, inboxHtml, plainEmailHtml, attachmentMetadata, isInboxAlias } from './inboxContent.js';
import { matchInboxContact } from './inboxMail.js';

// Route only through a verified receiving domain or an exact issued alias.
// Never infer a tenant from From, subject, a user-supplied account id, or a
// cosmetic sender slug on GigWorks' shared sending domain.
export async function resolveInboxTarget(data, db = prisma) {
  const addresses = inboundAddresses(data);
  const aliases = addresses.filter(isInboxAlias);
  if (aliases.length) {
    return db.inboxThread.findFirst({ where: { OR: [{ replyAlias: { in: aliases } }, { replyAliases: { hasSome: aliases } }] } });
  }
  // Invalid legacy/tracked aliases must not silently turn into new mail.
  if (addresses.some((a) => a.startsWith('reply+'))) return null;
  const domains = [...new Set(addresses.map((a) => a.split('@')[1]))];
  const matches = await db.emailDomain.findMany({ where: { domain: { in: domains }, receivingStatus: 'verified' } });
  if (matches.length !== 1) return null;
  const domain = matches[0];
  const recipient = addresses.find((a) => a.endsWith(`@${domain.domain}`));
  return { accountId: domain.accountId, recipient };
}

export async function receiveInboxMail(target, full, eventData, db = prisma) {
  const from = mailbox(full.from || eventData.from);
  if (!from) throw new Error('Received email has no valid sender.');
  const providerMessageId = eventData.email_id;
  if (!providerMessageId) throw new Error('Received email has no provider id.');
  const subject = String(full.subject || eventData.subject || '(No subject)').slice(0, 500);
  // No automatic reply is sent, avoiding vacation/bounce loops.
  try {
    return await withSerializableTransaction(db, async (tx) => {
      if (await tx.inboxMessage.findUnique({ where: { providerMessageId } })) return { duplicate: true };
      let thread = target.id ? await tx.inboxThread.findFirst({ where: { id: target.id, accountId: target.accountId } }) : null;
      if (target.id && !thread) throw new Error('Inbox conversation no longer exists.');
      if (!thread) {
        const contact = await matchInboxContact(target.accountId, from, tx);
        const id = randomUUID();
        const domain = target.recipient.split('@')[1];
        thread = await tx.inboxThread.create({ data: { id, accountId: target.accountId, contactEmail: from, subject, ...contact, replyAlias: `inbox+${id}@${domain}`, replyAliases: [`inbox+${id}@${domain}`] } });
      }
      const message = await tx.inboxMessage.create({ data: {
        threadId: thread.id, direction: 'inbound', fromAddress: from,
        toAddress: target.recipient || thread.replyAlias,
        subject, body: inboxHtml(full.html || plainEmailHtml(full.text || '')),
        providerMessageId, deliveryStatus: 'received',
        internetMessageId: typeof full.message_id === 'string' && !/[\r\n]/.test(full.message_id) ? full.message_id.slice(0, 998) : null,
        attachments: { create: attachmentMetadata(full.attachments) },
      } });
      await tx.inboxThread.update({ where: { id: thread.id }, data: { lastMessageAt: message.createdAt, archivedAt: null } });
      const owner = await tx.membership.findFirst({ where: { accountId: thread.accountId, role: 'owner' } });
      const accountData = await tx.accountData.findUnique({ where: { accountId: thread.accountId } });
      const emailEnabled = accountData?.data?.inboxSettings?.emailNotifications !== false;
      await tx.reminder.upsert({
        where: { accountId_relatedType_relatedId_ruleKey: { accountId: thread.accountId, relatedType: 'inbox', relatedId: thread.id, ruleKey: 'inbox-unread' } },
        create: { accountId: thread.accountId, createdByUserId: owner?.userId, relatedType: 'inbox', relatedId: thread.id, relatedName: 'Shared inbox', ruleKey: 'inbox-unread', autoGenerated: true, note: 'A new email is waiting in your GigWorks inbox.', remindAt: new Date(), emailEnabled },
        update: { completedAt: null, remindAt: new Date(), emailEnabled, emailSentAt: null },
      });
      return { threadId: thread.id };
    });
  } catch (error) {
    if (error.code === 'P2002') return { duplicate: true };
    throw error;
  }
}
