import { prisma } from './prisma.js';
import { notificationSettings, invoiceReminderStart, nextInvoiceReminder } from './notificationRules.js';

export const INQUIRY_RULE = 'inquiry-awaiting-review';
export const INVOICE_RULES = ['invoice-open-owner', 'invoice-open-client'];
export const NOTIFICATION_RULES = [INQUIRY_RULE, ...INVOICE_RULES];

async function accountContext(accountId, db) {
  const [data, members] = await Promise.all([
    db.accountData.findUnique({ where: { accountId } }),
    db.membership.findMany({ where: { accountId }, include: { user: true } }),
  ]);
  return { settings: notificationSettings(data?.data?.reminderSettings), members };
}
function recipientId(members, email) {
  return (members.find((m) => m.user?.email?.toLowerCase() === email?.toLowerCase()) || members.find((m) => m.role === 'owner'))?.userId;
}
export async function syncInquiryNotification(link, db = prisma) {
  const { settings, members } = await accountContext(link.accountId, db);
  const active = link.status === 'submitted';
  const enabled = active && (settings.inquiryEmailEnabled || settings.inquiryReminderEnabled);
  const where = { accountId_relatedType_relatedId_ruleKey: { accountId: link.accountId, relatedType: 'inquiry', relatedId: link.id, ruleKey: INQUIRY_RULE } };
  if (!enabled) {
    await db.reminder.updateMany({ where: { accountId: link.accountId, relatedId: link.id, ruleKey: INQUIRY_RULE, emailClaimedAt: null }, data: { completedAt: new Date(), emailEnabled: false } });
    return;
  }
  const data = {
    createdByUserId: recipientId(members, link.ownerEmail),
    relatedName: link.recipientName || 'New inquiry',
    note: `Review the new inquiry from ${link.recipientName || link.response?.firstName || 'a prospective client'} and apply it to a booking.`,
    emailEnabled: settings.inquiryEmailEnabled,
    completedAt: null,
  };
  await db.reminder.upsert({ where, create: { ...where.accountId_relatedType_relatedId_ruleKey, ...data, autoGenerated: true, remindAt: new Date() }, update: data });
}

export async function syncInvoiceNotifications(invoice, db = prisma, now = new Date()) {
  const { settings, members } = await accountContext(invoice.accountId, db);
  const booking = await db.booking.findFirst({ where: { id: invoice.bookingId, accountId: invoice.accountId } });
  const start = settings.invoiceRemindersEnabled ? invoiceReminderStart(invoice, booking, settings) : null;
  for (const ruleKey of INVOICE_RULES) {
    const audience = ruleKey.endsWith('client') ? 'client' : 'owner';
    const enabled = start && (settings.invoiceReminderRecipient === 'both' || settings.invoiceReminderRecipient === audience);
    const identity = { accountId: invoice.accountId, relatedType: 'invoice', relatedId: invoice.id, ruleKey };
    const where = { accountId_relatedType_relatedId_ruleKey: identity };
    const existing = await db.reminder.findUnique({ where });
    if (!enabled) {
      if (existing) await db.reminder.updateMany({ where: { id: existing.id, emailClaimedAt: null }, data: { completedAt: now, emailEnabled: false } });
      continue;
    }
    if (existing?.emailClaimedAt) continue;
    const remindAt = nextInvoiceReminder(start, existing?.emailSentAt, settings.invoiceRepeatDays);
    const data = {
      createdByUserId: recipientId(members, invoice.ownerEmail),
      relatedName: `Invoice #${invoice.displayNumber}`,
      note: `Invoice #${invoice.displayNumber}${invoice.recipientName ? ` for ${invoice.recipientName}` : ''} has an outstanding balance${invoice.dueDate ? ` due ${new Date(invoice.dueDate).toISOString().slice(0, 10)}` : ''}.`,
      emailEnabled: true,
      completedAt: null,
      remindAt,
    };
    // Preserve last delivery until the next occurrence is due; it anchors the cadence.
    if (existing?.emailSentAt && remindAt <= now) data.emailSentAt = null;
    await db.reminder.upsert({ where, create: { ...identity, ...data, autoGenerated: true }, update: data });
  }
}

export async function syncNotificationAutomations(db = prisma) {
  // Retire the old one-shot overdue rule to avoid duplicate invoice alerts.
  await db.reminder.updateMany({ where: { ruleKey: 'invoice-overdue', autoGenerated: true, completedAt: null, emailClaimedAt: null }, data: { completedAt: new Date(), emailEnabled: false } });
  const inquiries = await db.inquiryLink.findMany({ where: { status: 'submitted' } });
  for (const inquiry of inquiries) await syncInquiryNotification(inquiry, db);
  const invoices = await db.invoice.findMany({ where: { status: { in: ['sent', 'partial'] } } });
  for (const invoice of invoices) await syncInvoiceNotifications(invoice, db);
  const pending = await db.reminder.findMany({ where: { ruleKey: { in: NOTIFICATION_RULES }, completedAt: null, emailClaimedAt: null } });
  const inquiryIds = new Set(inquiries.map((i) => i.id));
  const invoiceIds = new Set(invoices.map((i) => i.id));
  const resolved = pending.filter((r) => !(r.ruleKey === INQUIRY_RULE ? inquiryIds : invoiceIds).has(r.relatedId));
  if (resolved.length) await db.reminder.updateMany({ where: { id: { in: resolved.map((r) => r.id) }, emailClaimedAt: null }, data: { completedAt: new Date(), emailEnabled: false } });
}

// Recheck immediately before delivery so payments, reviews and settings changes
// between the rule scan and the email scan cannot cause stale notifications.
export async function notificationDeliveryAllowed(reminder, db = prisma, now = new Date()) {
  if (!NOTIFICATION_RULES.includes(reminder.ruleKey)) return true;
  const { settings } = await accountContext(reminder.accountId, db);
  if (reminder.ruleKey === INQUIRY_RULE) {
    const link = await db.inquiryLink.findFirst({ where: { id: reminder.relatedId, accountId: reminder.accountId } });
    return settings.inquiryEmailEnabled && link?.status === 'submitted';
  }
  const invoice = await db.invoice.findFirst({ where: { id: reminder.relatedId, accountId: reminder.accountId } });
  if (!invoice || !settings.invoiceRemindersEnabled) return false;
  const audience = reminder.ruleKey.endsWith('client') ? 'client' : 'owner';
  if (settings.invoiceReminderRecipient !== 'both' && settings.invoiceReminderRecipient !== audience) return false;
  const booking = await db.booking.findFirst({ where: { id: invoice.bookingId, accountId: invoice.accountId } });
  const start = invoiceReminderStart(invoice, booking, settings);
  return !!start && start <= now;
}
