import { prisma } from './prisma.js';

// Deliberately much slower than reminderScheduler.js's 60s send-loop — these
// conditions (an event's date, an invoice's due date, a vendor's confirmed
// status) don't change minute-to-minute, so there's no value in polling at
// the same cadence as the actual email sender.
const POLL_INTERVAL_MS = 15 * 60 * 1000;

// V1 thresholds are fixed, not per-account configurable — a clean fast-
// follow once the mechanism itself is proven.
const EVENT_AT_RISK_DAYS = 3;
const INVOICE_OVERDUE_DAYS = 3;

const EVENT_RULE_KEY = 'event-unconfirmed';
const INVOICE_RULE_KEY = 'invoice-overdue';

function todayISO() {
  return new Date().toISOString().slice(0, 10);
}
function addDaysISO(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

// Same "is every assigned vendor confirmed" logic as DataContext.jsx's
// computeVendorStatus on the frontend, replicated here since this runs
// server-side with no access to that hook. `event.contractorBookings` is
// { contractorId, inquiryStatusId, ... }[]; inquiryStatuses is the small
// per-account status list embedded in AccountData.data.
function isVendorPending(event, inquiryStatuses) {
  if (!event.contractorBookings?.length) return false;
  const byId = new Map((inquiryStatuses || []).map((s) => [s.id, s]));
  return event.contractorBookings.some((b) => !byId.get(b.inquiryStatusId)?.isConfirmed);
}

async function getOwnerUserIdsByAccount(accountIds) {
  if (!accountIds.length) return new Map();
  const owners = await prisma.membership.findMany({
    where: { accountId: { in: accountIds }, role: 'owner' },
    select: { accountId: true, userId: true },
  });
  return new Map(owners.map((m) => [m.accountId, m.userId]));
}

// Idempotent across ticks: the `@@unique([accountId, relatedType, relatedId,
// ruleKey])` constraint (server/prisma/schema.prisma's Reminder model) means
// only the first tick that spots a qualifying record actually creates
// anything — `skipDuplicates` makes every later tick's batch a no-op against
// rows that already exist, whether still pending, already sent, or completed.
async function createAutoReminders(rows) {
  if (!rows.length) return;
  await prisma.reminder.createMany({
    data: rows.map((row) => ({ ...row, autoGenerated: true, remindAt: new Date(), emailEnabled: true })),
    skipDuplicates: true,
  });
}

async function createEventReminders() {
  const candidates = await prisma.event.findMany({
    where: { deletedAt: null, completedAt: null, eventDate: { gte: todayISO(), lte: addDaysISO(EVENT_AT_RISK_DAYS) } },
    select: { id: true, accountId: true, name: true, eventDate: true, contractorBookings: true },
  });
  if (!candidates.length) return;

  const accountIds = [...new Set(candidates.map((e) => e.accountId))];
  const [accountDataRows, ownerUserIdsByAccount] = await Promise.all([
    prisma.accountData.findMany({ where: { accountId: { in: accountIds } }, select: { accountId: true, data: true } }),
    getOwnerUserIdsByAccount(accountIds),
  ]);
  const inquiryStatusesByAccount = new Map(accountDataRows.map((row) => [row.accountId, row.data?.inquiryStatuses || []]));

  const toCreate = [];
  for (const event of candidates) {
    if (!isVendorPending(event, inquiryStatusesByAccount.get(event.accountId))) continue;
    const createdByUserId = ownerUserIdsByAccount.get(event.accountId);
    if (!createdByUserId) continue; // no owner membership found — nothing sane to send from
    toCreate.push({
      accountId: event.accountId,
      createdByUserId,
      relatedType: 'event',
      relatedId: event.id,
      relatedName: event.name || 'Untitled event',
      ruleKey: EVENT_RULE_KEY,
      note: `${event.name || 'This event'} is on ${event.eventDate} and still has an unconfirmed vendor.`,
    });
  }
  await createAutoReminders(toCreate);
}

async function createInvoiceReminders() {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - INVOICE_OVERDUE_DAYS);
  const candidates = await prisma.invoice.findMany({
    where: { status: { in: ['sent', 'partial'] }, dueDate: { lt: cutoff } },
    select: { id: true, accountId: true, number: true, recipientName: true, dueDate: true },
  });
  if (!candidates.length) return;

  const accountIds = [...new Set(candidates.map((i) => i.accountId))];
  const ownerUserIdsByAccount = await getOwnerUserIdsByAccount(accountIds);

  const toCreate = [];
  for (const invoice of candidates) {
    const createdByUserId = ownerUserIdsByAccount.get(invoice.accountId);
    if (!createdByUserId) continue; // no owner membership found — nothing sane to send from
    toCreate.push({
      accountId: invoice.accountId,
      createdByUserId,
      relatedType: 'invoice',
      relatedId: invoice.id,
      relatedName: invoice.recipientName || `Invoice #${invoice.number}`,
      ruleKey: INVOICE_RULE_KEY,
      note: `Invoice #${invoice.number}${invoice.recipientName ? ` for ${invoice.recipientName}` : ''} is overdue (was due ${invoice.dueDate.toISOString().slice(0, 10)}).`,
    });
  }
  await createAutoReminders(toCreate);
}

// Auto-generated reminders whose underlying condition has since resolved
// (event fully confirmed, invoice paid/void/deleted) get soft-completed so
// they never fire a stale email — a reminder about an already-solved
// problem would undermine trust in the whole feature. Only touches rows
// the email sender hasn't already claimed or sent (see reminderScheduler.js
// for that claim mechanism), so this can never race a send in flight.
async function completeResolvedReminders() {
  const pending = await prisma.reminder.findMany({
    where: {
      autoGenerated: true,
      ruleKey: { in: [EVENT_RULE_KEY, INVOICE_RULE_KEY] },
      emailSentAt: null,
      emailClaimedAt: null,
      completedAt: null,
    },
    select: { id: true, relatedType: true, relatedId: true },
  });
  if (!pending.length) return;

  const eventIds = pending.filter((r) => r.relatedType === 'event').map((r) => r.relatedId);
  const invoiceIds = pending.filter((r) => r.relatedType === 'invoice').map((r) => r.relatedId);

  const events = eventIds.length
    ? await prisma.event.findMany({ where: { id: { in: eventIds } }, select: { id: true, accountId: true, deletedAt: true, completedAt: true, contractorBookings: true } })
    : [];
  const eventAccountIds = [...new Set(events.map((e) => e.accountId))];
  const [accountDataRows, invoices] = await Promise.all([
    eventAccountIds.length
      ? prisma.accountData.findMany({ where: { accountId: { in: eventAccountIds } }, select: { accountId: true, data: true } })
      : [],
    invoiceIds.length
      ? prisma.invoice.findMany({ where: { id: { in: invoiceIds } }, select: { id: true, status: true } })
      : [],
  ]);
  const eventsById = new Map(events.map((e) => [e.id, e]));
  const inquiryStatusesByAccount = new Map(accountDataRows.map((row) => [row.accountId, row.data?.inquiryStatuses || []]));
  const invoicesById = new Map(invoices.map((i) => [i.id, i]));

  const toComplete = [];
  for (const reminder of pending) {
    if (reminder.relatedType === 'event') {
      const event = eventsById.get(reminder.relatedId);
      const stillAtRisk = event && !event.deletedAt && !event.completedAt && isVendorPending(event, inquiryStatusesByAccount.get(event.accountId));
      if (!stillAtRisk) toComplete.push(reminder.id);
    } else {
      const invoice = invoicesById.get(reminder.relatedId);
      const stillOverdue = invoice && (invoice.status === 'sent' || invoice.status === 'partial');
      if (!stillOverdue) toComplete.push(reminder.id);
    }
  }
  if (!toComplete.length) return;

  await prisma.reminder.updateMany({
    where: { id: { in: toComplete }, emailClaimedAt: null, emailSentAt: null, completedAt: null },
    data: { completedAt: new Date() },
  });
}

let running = false;
// Exported (not just used internally by startReminderRuleEngine below) so a
// test/ops script can trigger one pass on demand instead of waiting up to
// POLL_INTERVAL_MS for the next automatic run.
export async function tick() {
  if (running) return;
  running = true;
  try {
    await createEventReminders();
    await createInvoiceReminders();
    await completeResolvedReminders();
  } catch (err) {
    console.error('Reminder rule engine tick failed:', err);
  } finally {
    running = false;
  }
}

export function startReminderRuleEngine() {
  setInterval(tick, POLL_INTERVAL_MS);
}
