-- AlterTable
ALTER TABLE "Reminder" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ruleKey" TEXT;

-- CreateTable
CREATE TABLE "ClientPortalToken" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "usedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ClientPortalToken_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ClientPortalToken_tokenHash_key" ON "ClientPortalToken"("tokenHash");

-- CreateIndex
CREATE INDEX "ClientPortalToken_clientId_idx" ON "ClientPortalToken"("clientId");

-- CreateIndex
CREATE UNIQUE INDEX "Reminder_accountId_relatedType_relatedId_ruleKey_key" ON "Reminder"("accountId", "relatedType", "relatedId", "ruleKey");

-- AddForeignKey
ALTER TABLE "ClientPortalToken" ADD CONSTRAINT "ClientPortalToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

