import { useState } from 'react';
import Badge from './ui/Badge';
import { buildWhatsAppClickToChatUrl, formatCurrency as currency, formatEventTime, isValidEmailAddress } from '../lib/format';
import { getPricingTier, getPricingTiers, getOvertimeHours, getOvertimeAmount } from '../lib/pricingTiers';
import { BUCKETS, statusBucket } from '../lib/inquiryStatusBucket';

const controlClass = 'min-h-10 rounded-lg border border-slate-300 bg-white px-2.5 text-xs text-slate-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100';
const PAYMENT_METHOD_LABELS = { ach: 'ACH', check: 'Check', card: 'Card', cash: 'Cash', wire: 'Wire', other: 'Other' };
const requestStyle = { submitted: 'bg-amber-100 text-amber-800', approved: 'bg-emerald-100 text-emerald-700', disputed: 'bg-rose-100 text-rose-700', paid: 'bg-indigo-100 text-indigo-700' };
const requestLabel = { submitted: 'Request needs review', approved: 'Request approved', disputed: 'Request returned', paid: 'Request paid' };

function MailIcon() {
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-5 w-5"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m3 7 9 6 9-6" /></svg>;
}

function SmsIcon() {
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-5 w-5"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z" /><path d="M8 10h.01M12 10h.01M16 10h.01" strokeLinecap="round" strokeWidth="2.5" /></svg>;
}

function WhatsAppIcon() {
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5"><path d="M12.04 2a9.84 9.84 0 0 0-8.53 14.74L2 22l5.39-1.41A9.98 9.98 0 1 0 12.04 2Zm0 17.98a8.1 8.1 0 0 1-4.13-1.13l-.3-.18-3.2.84.86-3.12-.2-.32A8.09 8.09 0 1 1 12.04 19.98Zm4.44-6.06c-.24-.12-1.44-.71-1.66-.79-.22-.08-.38-.12-.54.12-.16.24-.63.79-.77.95-.14.16-.28.18-.52.06-.24-.12-1.03-.38-1.96-1.21a7.34 7.34 0 0 1-1.35-1.68c-.14-.24-.02-.37.1-.49.11-.11.24-.28.36-.42.12-.14.16-.24.24-.4.08-.16.04-.3-.02-.42-.06-.12-.54-1.3-.74-1.78-.2-.47-.4-.41-.54-.42h-.46a.88.88 0 0 0-.63.3c-.22.24-.83.81-.83 1.97 0 1.16.85 2.29.97 2.45.12.16 1.67 2.55 4.05 3.58.56.24 1 .39 1.35.5.57.18 1.08.15 1.49.09.45-.07 1.44-.59 1.64-1.16.2-.57.2-1.05.14-1.16-.06-.1-.22-.16-.46-.28Z" /></svg>;
}

export default function ContractorPickerRow({ booking, contractor, eventName, eventDate, inquiryStatuses, index, emailTemplates, threadSummary, onStatusChange, onRemove, onRequestSend, onOpenContractor, onOpenThread, onTierChange, onTimeChange, onOvertimeChange, onPayClick, onMarkUnpaid, paymentRequest, onReviewPaymentRequest, onDragStart, onDragOver, onDrop, isDragging }) {
  const [selectedTemplateId, setSelectedTemplateId] = useState('');
  const [editing, setEditing] = useState(false);
  if (!contractor) return null;

  const status = inquiryStatuses.find((item) => item.id === booking.inquiryStatusId);
  const currentBucket = statusBucket(status);
  const unreadCount = threadSummary?.unreadCount || 0;
  const hasValidEmail = isValidEmailAddress(contractor.email);
  // Keep the destination explicitly tied to the contractor assigned to this
  // booking. The helper intentionally accepts `recipientPhone` rather than a
  // generic `phone`, preventing an account/user phone from being substituted
  // accidentally as more messaging settings are added.
  const contractorMatchesBooking = String(contractor.id) === String(booking.contractorId);
  const whatsAppUrl = buildWhatsAppClickToChatUrl({ recipientPhone: contractorMatchesBooking ? contractor.phone : '', contractorName: `${contractor.firstName || ''} ${contractor.lastName || ''}`, eventName, eventDate });
  const tiers = getPricingTiers(contractor);
  const activeTier = getPricingTier(contractor, booking.pricingTierId);
  const tierTracksOvertime = Number(activeTier?.includedHours) > 0 && Number(activeTier?.overtimeRate) > 0;
  const isManualOvertime = booking.overtimeHoursOverride !== null && booking.overtimeHoursOverride !== undefined && booking.overtimeHoursOverride !== '';
  const overtimeHours = tierTracksOvertime ? getOvertimeHours(booking, contractor) : 0;
  const overtimeAmount = tierTracksOvertime ? getOvertimeAmount(booking, contractor) : 0;
  const bucketStripClass = { confirmed: 'border-l-green-400', tentative: 'border-l-yellow-400', unavailable: 'border-l-red-400' }[currentBucket] || 'border-l-indigo-400';

  return <div draggable onDragStart={() => onDragStart(index)} onDragOver={(event) => { event.preventDefault(); onDragOver(index); }} onDrop={() => onDrop(index)} data-testid="contractor-picker-row" className={`rounded-xl border border-l-4 border-slate-200 bg-white ${bucketStripClass} ${isDragging ? 'opacity-40' : ''}`}>
    <div className="flex flex-wrap items-center gap-2.5 p-3">
      <span className="cursor-grab select-none text-slate-300" aria-hidden="true">⠿</span>
      <button type="button" onClick={() => onOpenContractor(contractor)} data-testid="contractor-picker-row-name-button" className="min-w-[10rem] flex-1 text-left"><span className="block truncate text-sm font-semibold text-slate-800 hover:text-indigo-600">{contractor.firstName} {contractor.lastName}</span><span className="block truncate text-xs text-slate-500">{contractor.contractorType1}{contractor.contractorType2 ? ` · ${contractor.contractorType2}` : ''}</span></button>
      <div className="flex shrink-0 items-center gap-1" aria-label="Contractor communication channels">
        <button type="button" onClick={() => onOpenThread(booking.contractorId)} data-testid="contractor-picker-row-email-history-button" aria-label="Open contact history" title="Contact History" className="relative flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-600"><MailIcon />{unreadCount > 0 && <span className="absolute -right-1.5 -top-1.5 min-w-5 rounded-full bg-red-500 px-1 text-[10px] font-bold leading-5 text-white">{unreadCount}</span>}</button>
        <span className="group relative inline-flex" tabIndex={0}><button type="button" disabled aria-label="SMS coming soon" aria-describedby="coming-soon-sms" className="flex h-10 w-10 cursor-not-allowed items-center justify-center rounded-lg border border-slate-200 bg-slate-100 text-slate-400"><SmsIcon /></button><span id="coming-soon-sms" role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 z-20 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-md bg-slate-900 px-2 py-1 text-[11px] font-semibold text-white shadow-lg group-hover:block group-focus:block">Coming soon</span></span>
        {whatsAppUrl ? <span className="group relative inline-flex"><a href={whatsAppUrl} target="_blank" rel="noreferrer" data-testid="contractor-picker-row-whatsapp-link" data-recipient-phone={contractor.phone} aria-label={`Open WhatsApp chat with ${contractor.firstName} ${contractor.lastName} at ${contractor.phone}. Messages will not be tracked in GigWorks.`} aria-describedby={`whatsapp-disclaimer-${booking.contractorId}`} className="flex h-10 w-10 items-center justify-center rounded-lg border border-emerald-200 bg-emerald-50 text-emerald-600 hover:border-emerald-300 hover:bg-emerald-100 hover:text-emerald-700"><WhatsAppIcon /></a><span id={`whatsapp-disclaimer-${booking.contractorId}`} role="tooltip" className="pointer-events-none absolute bottom-full right-0 z-20 mb-2 hidden w-64 rounded-md bg-slate-900 px-3 py-2 text-left text-[11px] font-semibold leading-relaxed text-white shadow-lg group-hover:block group-focus-within:block">Opens WhatsApp with {contractor.firstName} {contractor.lastName} at {contractor.phone}. Messages and replies will not be tracked or saved in Contact History.</span></span> : <span className="group relative inline-flex" tabIndex={0}><button type="button" disabled aria-label="WhatsApp unavailable because the contractor phone number is missing or invalid" aria-describedby={`whatsapp-unavailable-${booking.contractorId}`} className="flex h-10 w-10 cursor-not-allowed items-center justify-center rounded-lg border border-slate-200 bg-slate-100 text-emerald-300"><WhatsAppIcon /></button><span id={`whatsapp-unavailable-${booking.contractorId}`} role="tooltip" className="pointer-events-none absolute bottom-full right-0 z-20 mb-2 hidden whitespace-nowrap rounded-md bg-slate-900 px-2 py-1 text-[11px] font-semibold text-white shadow-lg group-hover:block group-focus:block">Add a valid phone number</span></span>}
      </div>
      <span className="shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold" style={status ? { color: status.color, backgroundColor: `${status.color}15` } : undefined}>{status?.label || 'Status not set'}</span>
      <div className="min-w-20 text-right"><span className="block text-sm font-bold text-slate-700">{currency(activeTier?.price)}</span>{tiers.length > 1 && <span className="block text-[11px] text-slate-400">{activeTier?.name}</span>}</div>
      {paymentRequest && <button type="button" onClick={() => onReviewPaymentRequest(paymentRequest)} data-testid="contractor-picker-row-payment-request-button" title={paymentRequest.note || 'Open payment request'} className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${requestStyle[paymentRequest.status] || requestStyle.submitted}`}>{requestLabel[paymentRequest.status] || 'Payment request'}</button>}
      {currentBucket === 'confirmed' && (booking.paymentStatus === 'paid' ? <div className="flex shrink-0 items-center gap-1"><button type="button" onClick={() => onPayClick(booking.contractorId)} title={`${currency(booking.paidAmount)}${booking.paymentMethod ? ` via ${PAYMENT_METHOD_LABELS[booking.paymentMethod] || booking.paymentMethod}` : ''}`} data-testid="contractor-picker-row-paid-badge-button"><Badge color="#22c55e">Paid</Badge></button><button type="button" onClick={() => onMarkUnpaid(booking.contractorId)} className="px-1 text-slate-300 hover:text-red-600" aria-label="Mark unpaid" data-testid="contractor-picker-row-mark-unpaid-button">✕</button></div> : <button type="button" onClick={() => onPayClick(booking.contractorId)} data-testid="contractor-picker-row-pay-button" className="min-h-10 shrink-0 rounded-lg border border-emerald-300 px-3 text-xs font-semibold text-emerald-700 hover:bg-emerald-50">Pay</button>)}
      <button type="button" onClick={() => setEditing((value) => !value)} aria-expanded={editing} data-testid="contractor-picker-row-details-button" className={`min-h-10 shrink-0 rounded-lg px-3 text-xs font-semibold ${editing ? 'bg-indigo-600 text-white' : 'border border-slate-200 text-indigo-600 hover:bg-indigo-50'}`}>{editing ? 'Done' : 'Edit'}</button>
      <button type="button" onClick={() => onRemove(booking.contractorId)} className="flex h-10 w-8 shrink-0 items-center justify-center rounded-lg text-slate-300 hover:bg-red-50 hover:text-red-600" aria-label="Remove contractor" data-testid="contractor-picker-row-remove-button">✕</button>
    </div>
    {!editing && <div data-testid="contractor-picker-row-readonly-details" className="grid gap-x-5 gap-y-2 border-t border-slate-100 bg-slate-50/50 px-3 py-3 text-xs sm:grid-cols-2 lg:grid-cols-4 sm:pl-9">
      <div><span className="font-semibold text-slate-400">Schedule</span><p className="mt-0.5 font-medium text-slate-700">{formatEventTime(booking.startTime) || 'Start TBD'} – {formatEventTime(booking.endTime) || 'End TBD'}</p></div>
      <div><span className="font-semibold text-slate-400">Rate</span><p className="mt-0.5 font-medium text-slate-700">{currency(activeTier?.price)}{activeTier?.name ? ` · ${activeTier.name}` : ''}{overtimeAmount > 0 ? ` · +${currency(overtimeAmount)} OT` : ''}</p></div>
      <div><span className="font-semibold text-slate-400">Payment</span><p className={`mt-0.5 font-semibold ${booking.paymentStatus === 'paid' ? 'text-emerald-700' : 'text-slate-600'}`}>{booking.paymentStatus === 'paid' ? `Paid ${currency(booking.paidAmount)}${booking.paidAt ? ` on ${booking.paidAt}` : ''}${booking.paymentMethod ? ` via ${PAYMENT_METHOD_LABELS[booking.paymentMethod] || booking.paymentMethod}` : ''}` : `Not paid${booking.paymentDueDate ? ` · due ${booking.paymentDueDate}` : ''}`}</p></div>
      <div><span className="font-semibold text-slate-400">Payment request</span>{paymentRequest ? <div className="mt-0.5 text-slate-700"><button type="button" onClick={() => onReviewPaymentRequest(paymentRequest)} className="font-semibold text-indigo-600 hover:underline">{requestLabel[paymentRequest.status] || 'Payment request'} · {currency(paymentRequest.amount)}</button>{paymentRequest.invoiceNumber && <p className="mt-0.5">Ref: {paymentRequest.invoiceNumber}</p>}{paymentRequest.note && <p className="mt-0.5 line-clamp-2" title={paymentRequest.note}>{paymentRequest.note}</p>}{paymentRequest.reviewNote && <p className="mt-1 text-rose-700">Update requested: {paymentRequest.reviewNote}</p>}</div> : <p className="mt-0.5 text-slate-500">No request submitted</p>}</div>
    </div>}
    {editing && <div className="border-t border-indigo-100 bg-indigo-50/40 px-3 py-3 sm:pl-9"><div className="flex flex-wrap items-end gap-2.5">
      <label className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Status<select value={booking.inquiryStatusId || ''} onChange={(event) => onStatusChange(booking.contractorId, event.target.value)} aria-label={`Status for ${contractor.firstName} ${contractor.lastName}`} data-testid="contractor-picker-row-status-select" className={`${controlClass} mt-1 block w-40 normal-case`}>{BUCKETS.map((bucket) => <optgroup key={bucket.value} label={bucket.label}>{inquiryStatuses.filter((item) => statusBucket(item) === bucket.value).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</optgroup>)}</select></label>
      {emailTemplates.length > 0 && hasValidEmail && <><select value={selectedTemplateId} onChange={(event) => setSelectedTemplateId(event.target.value)} data-testid="contractor-picker-row-template-select" className={`${controlClass} w-40`}><option value="">Select email…</option>{emailTemplates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select><button type="button" onClick={() => selectedTemplateId && onRequestSend(booking.contractorId, selectedTemplateId)} disabled={!selectedTemplateId} data-testid="contractor-picker-row-send-email-button" className="min-h-10 rounded-lg border border-indigo-300 px-3 text-xs font-semibold text-indigo-600 disabled:opacity-40">Send</button></>}
      {!hasValidEmail && <span className="self-center text-xs font-semibold text-amber-700">Email required before sending</span>}
      {tiers.length > 1 && <label className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Rate<select value={activeTier?.id || ''} onChange={(event) => onTierChange(booking.contractorId, event.target.value)} data-testid="contractor-picker-row-tier-select" className={`${controlClass} mt-1 block w-32 normal-case`}>{tiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label>}
      <label className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Start<input type="time" value={booking.startTime || ''} onChange={(event) => onTimeChange(booking.contractorId, 'startTime', event.target.value)} data-testid="contractor-picker-row-start-time-input" className={`${controlClass} mt-1 block`} /></label>
      <label className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">End<input type="time" value={booking.endTime || ''} onChange={(event) => onTimeChange(booking.contractorId, 'endTime', event.target.value)} data-testid="contractor-picker-row-end-time-input" className={`${controlClass} mt-1 block`} /></label>
      {tierTracksOvertime && <label className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">OT hours<input type="number" min="0" step="0.5" value={booking.overtimeHoursOverride ?? ''} placeholder={overtimeHours > 0 ? overtimeHours.toFixed(1) : '0'} onChange={(event) => onOvertimeChange(booking.contractorId, event.target.value === '' ? null : event.target.value)} title={isManualOvertime ? 'Manual override—clear to use Start and End time' : 'Calculated from Start and End time'} data-testid="contractor-picker-row-overtime-hours-input" className={`${controlClass} mt-1 block w-20`} /></label>}
      {overtimeAmount > 0 && <span data-testid="contractor-picker-row-overtime-amount" className="self-center text-xs font-semibold text-slate-600">+{currency(overtimeAmount)} overtime</span>}
    </div></div>}
  </div>;
}
