import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import MoneyInput from './ui/MoneyInput';
import { saveFinancialBudget } from '../lib/financials';

const money = (value) => Number(value || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const inputClass = 'w-full min-h-11 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100';

function TrendChart({ rows }) {
  const width = 720; const height = 190; const pad = 24;
  const values = rows.flatMap((row) => [row.income, row.expenses, row.profit]);
  const min = Math.min(0, ...values); const max = Math.max(1, ...values); const range = max - min || 1;
  const x = (index) => pad + (index * (width - pad * 2)) / Math.max(1, rows.length - 1);
  const y = (value) => pad + ((max - value) / range) * (height - pad * 2);
  const path = (key) => rows.map((row, index) => `${index ? 'L' : 'M'}${x(index).toFixed(1)},${y(row[key]).toFixed(1)}`).join(' ');
  return <div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="min-w-[620px] w-full h-52" role="img" aria-label="Twelve-month income, expense, and profit trend"><line x1={pad} y1={y(0)} x2={width - pad} y2={y(0)} stroke="#cbd5e1" strokeDasharray="4 4" /><path d={path('income')} fill="none" stroke="#10b981" strokeWidth="3" /><path d={path('expenses')} fill="none" stroke="#f43f5e" strokeWidth="3" /><path d={path('profit')} fill="none" stroke="#4f46e5" strokeWidth="3" />{rows.map((row, index) => <text key={row.key} x={x(index)} y={height - 5} textAnchor="middle" fontSize="9" fill="#94a3b8">{row.label.split(' ')[0]}</text>)}</svg></div>;
}

function SummaryCard({ label, value, note, color = 'text-slate-800' }) {
  return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-xl font-bold ${color}`}>{money(value)}</p>{note && <p className="mt-1 text-xs text-slate-400">{note}</p>}</div>;
}

export default function FinancialForecastDashboard({ forecast, groupId, canManage, onRefresh }) {
  const currentMonth = new Date().toISOString().slice(0, 7);
  const current = forecast.trend.find((row) => row.key === currentMonth) || forecast.trend.at(-1);
  const [revenueTarget, setRevenueTarget] = useState(String(current?.revenueTarget || ''));
  const [expenseBudget, setExpenseBudget] = useState(String(current?.expenseBudget || ''));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const sixMonthIn = forecast.cashFlow.reduce((sum, row) => sum + row.expectedIn, 0);
  const sixMonthOut = forecast.cashFlow.reduce((sum, row) => sum + row.expectedOut, 0);
  useEffect(() => { setRevenueTarget(String(current?.revenueTarget || '')); setExpenseBudget(String(current?.expenseBudget || '')); }, [current?.revenueTarget, current?.expenseBudget, groupId]);

  async function saveBudget(event) {
    event.preventDefault(); setSaving(true); setError('');
    try { await saveFinancialBudget(currentMonth, { groupId: groupId || null, revenueTarget, expenseBudget }); await onRefresh(); }
    catch (err) { setError(err.message || 'The monthly targets could not be saved.'); }
    finally { setSaving(false); }
  }

  return <section className="space-y-5" aria-labelledby="financial-forecast-title">
    <div><h2 id="financial-forecast-title" className="text-xl font-bold text-slate-900">Forecast and financial dashboard</h2><p className="mt-1 text-sm text-slate-500">Forward-looking cash, sales pipeline, targets, and financial risks.</p></div>
    {forecast.alerts.length > 0 && <div className="grid md:grid-cols-2 gap-3">{forecast.alerts.map((alert) => <Link key={alert.id} to={alert.path} className={`rounded-xl border p-4 ${alert.severity === 'high' ? 'border-rose-200 bg-rose-50' : 'border-amber-200 bg-amber-50'}`}><p className={`text-sm font-bold ${alert.severity === 'high' ? 'text-rose-800' : 'text-amber-800'}`}>{alert.title}</p><p className="mt-1 text-xs text-slate-600">{alert.detail}</p></Link>)}</div>}
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><SummaryCard label="Pipeline value" value={forecast.pipeline.total} note="Open proposals" /><SummaryCard label="Weighted forecast" value={forecast.pipeline.weightedTotal} note="Adjusted by sales stage" color="text-indigo-700" /><SummaryCard label="Expected collections" value={sixMonthIn} note="Next six months" color="text-emerald-700" /><SummaryCard label="Expected contractor pay" value={sixMonthOut} note="Next six months" color="text-rose-700" /></div>
    <div className="grid xl:grid-cols-[1.4fr_1fr] gap-5"><div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-slate-800">12-month cash trend</h3><p className="text-xs text-slate-500">Actual ledger activity</p></div><div className="flex gap-3 text-xs font-semibold"><span className="text-emerald-600">● Income</span><span className="text-rose-600">● Expenses</span><span className="text-indigo-600">● Profit</span></div></div><TrendChart rows={forecast.trend} /></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-800">This month’s targets</h3><p className="mt-1 text-xs text-slate-500">Set targets for the selected agency group or the whole account.</p>{error && <p className="mt-3 rounded-lg bg-rose-50 px-3 py-2 text-xs text-rose-700">{error}</p>}{canManage ? <form onSubmit={saveBudget} className="mt-4 space-y-3"><label className="block text-sm font-medium text-slate-700">Revenue target<MoneyInput value={revenueTarget} onChange={setRevenueTarget} className={`${inputClass} mt-1`} /></label><label className="block text-sm font-medium text-slate-700">Expense budget<MoneyInput value={expenseBudget} onChange={setExpenseBudget} className={`${inputClass} mt-1`} /></label><button disabled={saving} className="min-h-11 w-full rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save monthly targets'}</button></form> : <p className="mt-4 text-sm text-slate-500">You can view targets but do not have permission to change them.</p>}<div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-400">Revenue progress</p><p className="font-bold text-slate-700">{current?.revenueTarget > 0 ? `${Math.round((current.income / current.revenueTarget) * 100)}%` : 'Set target'}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-400">Budget used</p><p className="font-bold text-slate-700">{current?.expenseBudget > 0 ? `${Math.round((current.expenses / current.expenseBudget) * 100)}%` : 'Set budget'}</p></div></div></div></div>
    <div className="grid xl:grid-cols-2 gap-5"><div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-100"><h3 className="font-bold text-slate-800">Expected cash flow</h3><p className="text-xs text-slate-500">Open invoice balances minus unpaid contractor assignments.</p></div><div className="divide-y divide-slate-100">{forecast.cashFlow.map((row) => <div key={row.key} className="grid grid-cols-4 gap-2 px-5 py-3 text-sm"><span className="font-semibold text-slate-700">{row.label}</span><span className="text-right text-emerald-700">+{money(row.expectedIn)}</span><span className="text-right text-rose-700">−{money(row.expectedOut)}</span><span className={`text-right font-bold ${row.net >= 0 ? 'text-indigo-700' : 'text-rose-700'}`}>{money(row.net)}</span></div>)}</div></div><div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-100"><h3 className="font-bold text-slate-800">Weighted sales pipeline</h3><p className="text-xs text-slate-500">Probability is based on proposal and contract progress.</p></div><div className="divide-y divide-slate-100 max-h-80 overflow-y-auto">{forecast.pipeline.rows.length === 0 ? <p className="p-8 text-center text-sm text-slate-400">No priced opportunities found.</p> : forecast.pipeline.rows.map((row) => <Link key={row.bookingId} to={`/bookings/${row.bookingId}`} className="grid grid-cols-[1fr_auto] gap-3 px-5 py-3 hover:bg-slate-50"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-700">{row.name}</p><p className="text-xs text-slate-400">{row.stage} · {Math.round(row.probability * 100)}%</p></div><div className="text-right"><p className="text-sm font-bold text-slate-700">{money(row.weightedValue)}</p><p className="text-xs text-slate-400">of {money(row.value)}</p></div></Link>)}</div></div></div>
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-100"><h3 className="font-bold text-slate-800">Upcoming contractor obligations</h3><p className="text-xs text-slate-500">Unpaid assignments, ordered by event date.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Contractor</th><th className="px-5 py-3">Event</th><th className="px-5 py-3">Date</th><th className="px-5 py-3 text-right">Expected pay</th></tr></thead><tbody className="divide-y divide-slate-100">{forecast.obligations.length === 0 ? <tr><td colSpan="4" className="px-5 py-8 text-center text-slate-400">No unpaid contractor obligations.</td></tr> : forecast.obligations.map((row, index) => <tr key={`${row.eventId}-${row.contractorName}-${index}`}><td className="px-5 py-3 font-semibold text-slate-700">{row.contractorName}</td><td className="px-5 py-3"><Link to={`/events/${row.eventId}?tab=financials`} className="text-indigo-600">{row.eventName}</Link></td><td className="px-5 py-3 text-slate-500">{row.eventDate || 'Not scheduled'}</td><td className="px-5 py-3 text-right font-bold text-slate-700">{money(row.amount)}</td></tr>)}</tbody></table></div></div>
  </section>;
}
