CREATE TABLE "BackgroundJobLease" (
    "name" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BackgroundJobLease_pkey" PRIMARY KEY ("name")
);

CREATE INDEX "BackgroundJobLease_expiresAt_idx" ON "BackgroundJobLease"("expiresAt");

CREATE INDEX "reminder_due_email_idx"
ON "Reminder"("emailEnabled", "emailSentAt", "completedAt", "remindAt", "id");

CREATE INDEX "reminder_auto_resolution_idx"
ON "Reminder"("autoGenerated", "emailSentAt", "emailClaimedAt", "completedAt");
